name: "hsi3125_sgr101_fold1"        # name of this experiment. Used for comet-ml too
#name: "hsi_dilation_conv_fold1"        # name of this experiment. Used for comet-ml too
tags: ['standard', 'training']  # for comet-ml
gpu_id: ['1']                     # must set as a string, empty means using CPU
seed: 50
resume: True
dataset: 'pathology'  # dataset name
train_params:
  #dataset_dir: '/data/semantic_segmentation/data/UOW-HSI/'
  #dataset_dir: '/home/hieu/research/data/UOW-HSI/'
  dataset_dir: '/mnt/Windows/cv_projects/MHSI_Original/MHSI/'
  train_txtfiles: [ 'data-3125/P2_pathology.txt' ] # textfiles containing the data path for training
  test_txtfiles: 'data-3125/P1_pathology.txt'  # textfiles containing the data path for testing
  n_cutoff_imgs: ''
  batch_size: 1
  #batch_size: 54
  initial_epoch: 0
  n_epochs: 1000
  num_workers: 4
  early_stop: 1000
  class_weights: [0.03, 0.035, 0.035, 0.905, 0.025]
  #class_weights: [0, 0.035, 0.035, 0.905, 0.025]
  #save_dir: 'hsi_sd_pool_r_16_fold1-20210114-113413'
  #save_dir: 'hsi_res101_fold1-20210218-041728'
  save_dir: 'hsi3125_sgr101_fold1-20220414-184610'
optimizer:
  type: Adam
  args:
    lr: 0.0001

loss: KDLoss

metric: IoU

model_params:       # params for generating the S-Net model
  name: Res_SGR_Net
  encoder_name: 'resnet101'
  n_bands: 60
  classes: [0, 1]
  nf_enc: [64, 256, 512, 1024,2048]
  nf_dec: [64, 32, 32, 16, 16, 8]
  do_batchnorm: 1
  n_heads: 5
  feat_weight: 0.15
  resp_weight: 0.2
  student_weight: 1.0