name: "hsi3125_sgr101_fold1"        # name of this experiment. Used for comet-ml too
tags: ['standard', 'training']  # for comet-ml
gpu_id: ['1']                     # must set as a string, empty means using CPU
seed: 50
resume: True
dataset: 'bio'  # dataset name
train_params:
  dataset_dir: 'C:/Users/maria/Documents/Masters 24/New_Models/KDM_Model/KDM/bioDataset'
  train_txtfiles: ['data-3125/P6_Bio.txt'] # textfiles containing the data path for training
  test_txtfiles: 'data-3125/P7_Bio.txt'  # textfiles containing the data path for testing
  n_cutoff_imgs: ''
  batch_size: 1
  #batch_size: 54
  initial_epoch: 0
  n_epochs: 100
  num_workers: 4
  early_stop: 10
  class_weights: [0.03, 0.035, 0.035, 0.905, 0.025]
  save_dir: 'hsi3125_sgr101_fold1-20220414-184610/'
  add_cm_labels: 0
optimizer:
  type: Adam
  args:
    lr: 0.0001

loss: KDLoss

metric: MacroIoU

model_params:       # params for generating the S-Net model
  name: Res_SGR_Net
  encoder_name: 'resnet101'
  n_bands: 51
  classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
  nf_enc: [64, 256, 512, 1024,2048]
  nf_dec: [64, 32, 32, 16, 16, 8]
  do_batchnorm: 1
  n_heads: 5
  feat_weight: 0.15
  resp_weight: 0.2
  student_weight: 1.0
