name: 'spatial_transcriptomics_blkd'
seed: 42

dataset: 'spatial_transcriptomics'
gpu_id: [0]

train_params:
  dataset: 'spatial_transcriptomics'
  dataset_dir: '/content/KDM/KDM/bioDataset3'
  ##distillation_mode: 'block'  # Progressive head selection
  distillation_mode: 'best_only'  # Always use the last/best head
  batch_size: 16
  n_epochs: 100
  num_workers: 4
  save_dir: ''
  early_stop: 20
  ignore_index: 0

teacher_params:
  name: 'Res_SGR_Net'  # Same as your successful teacher
  n_bands: 136
  classes: [0, 1, 2, 3, 4, 5]
  n_heads: 5
  encoder_name: 'resnet50'  # Same as successful teacher
  
  # IMPORTANT: Use exact same channel progression as successful teacher
  nf_enc: [64, 256, 512, 1024, 2048]  # ResNet50 channels
  nf_dec: [1024, 512, 256, 128, 64, 32]  # Proper decoder progression
  
  do_batchnorm: true
  pretrained_file: 'experiments/spatial_transcriptomics_res_sgr-teacher-20250515-192311/best_model.pth'

student_params:
  name: 'HSINet'  # Simple student
  n_bands: 136
  classes: [0, 1, 2, 3, 4, 5]
  nf_enc: [32, 64, 128, 256]      # Much smaller than teacher
  nf_dec: [32, 16, 16, 8, 8, 4]   # Much smaller than teacher
  do_batchnorm: true
  feat_weight: 0.5
  resp_weight: 0.5
  temperature: 3.0

optimizer:
  type: 'Adam'
  args:
    lr: 0.0001
    weight_decay: 0.00001

loss: 'KnowledgeDistillationLoss'
metric: 'MeanIoU'
resume: false

tags: 
  - 'spatial_transcriptomics'
  - 'block_knowledge_distillation'
  - 'student'